default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres_db  # Este es el nombre del servicio de PostgreSQL en docker-compose.yml
  username: user
  password: password
  database: mydb
  pool: 5

development:
  <<: *default
  database: mydb_development

test:
  <<: *default
  database: mydb_test

production:
  <<: *default
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'postgres_db' %>
  database: <%= ENV['POSTGRES_DB'] || 'mydb_production' %>

