version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_server_dos
    networks:
      - app_network
    ports:
      - "5672:5672"
      - "15672:15672"
    
  ruby_app:
    build: .
    container_name: rails_app
    volumes:
      - ./rails_app:/app
      - ./rails_data:/app/data
    environment:
      - RAILS_ENV=development
    working_dir: /app
    command: bash -c "bundle install && bin/rails db:create db:migrate && bin/rails s -b '0.0.0.0'"
    networks:
      - app_network
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"

  python_app:
    build: ./flask_app
    container_name: flask_app
    volumes:
      - ./flask_app:/app  # Asegúrate de que tu código esté en esta carpeta
      - ./flask_data:/app/data
    environment:
      - FLASK_APP=app.py  # Especificamos explícitamente que el archivo de la app es app.py
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    networks:
      - app_network
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5000:5000"

networks:
  app_network:
    driver: bridge
